.PHONY: clean All

All:
	@echo "----------Building project:[ PhenobottleUI - Debug ]----------"
	@cd "PhenobottleUI/src" && "$(MAKE)" -f  "PhenobottleUI.mk"
clean:
	@echo "----------Cleaning project:[ PhenobottleUI - Debug ]----------"
	@cd "PhenobottleUI/src" && "$(MAKE)" -f  "PhenobottleUI.mk" clean
